Repository umicro/uView2.0, pull requests merged in 2022-01, with the labels that each got.

#286 feat(u-form):增加form表单提示，设置rules，未绑定model给予提示
  uni_modules/uview-ui/components/u-form/u-form.vue
Labels: enhancement

#184 修复微信小程序环境中tabbar组件开启safeAreaInsetBottom属性后，placeholder高度填充不正确
  uni_modules/uview-ui/components/u-tabbar/u-tabbar.vue
Labels: bug

#291 fix: swiper在current指定非0时缩放有误
  uni_modules/uview-ui/components/u-swiper/u-swiper.vue
Labels: bug

#290 fix: u-icon添加stop属性的时候报错
  uni_modules/uview-ui/components/u-icon/u-icon.vue
Labels: bug

#154 fix: u-image slot 加载和错误的图片失去了高度
  uni_modules/uview-ui/components/u-image/u-image.vue
Labels: bug, help wanted

#295 fix: u-index-list中footer插槽与header插槽存在性判断错误
  uni_modules/uview-ui/components/u-index-list/u-index-list.vue
Labels: bug

#288 feat nvue中u-popup关闭时会闪烁
  uni_modules/uview-ui/components/u-popup/u-popup.vue
Labels: bug, invalid
